
/******************************************************************************
 * DotNetMenu.java
 *
 * Copyright (C) SAS Institute, All rights reserved.
 * General Public License: https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * This file is automatically generated from XML source.  Any changes you make 
 * here will be erased the next time the file is generated.
 *
 * The following assets are needed to generate this file:
 *
 *   DotNetMenuFunctions.xml
 *   keyword_library.dtd
 *   XSLJavaCommonFunctions.xsl
 *   XSLJavaComponentModel.xsl
 *
 * Example invocation to generate:
 *
 *   msxsl.exe DotNetMenuFunctions.xml XSLJavaComponentModel.xsl -o DotNetMenu.java
 *
 ******************************************************************************/ 
package org.safs.model.components;

import org.safs.model.commands.DotNetMenuFunctions;
import org.safs.model.ComponentFunction;
import org.safs.model.components.UIComponent;
import org.safs.model.StepTestTable;

public class DotNetMenu extends JavaMenu {

    /*****************
    Constructor 

    Create an instance of pseudo-component representing 
    a specific component in a specific window.
    
    @param window  Optional:NO 
           Specifies which Window this component is 'in'.
    @param compname Optional:NO 
           Specifies the AppMap name of the component in the Window.
    ****************/
    public DotNetMenu(Window window, String compname) {

        super(window, compname);
    }

    /*****************
    Constructor 

    Create an instance of pseudo-component representing 
    a specific component in a specific window.
    
    This convenience routine will create the requisite Window component.
    
    @param winname  Optional:NO 
           Specifies the AppMap name of the window.
    @param compname Optional:NO 
           Specifies the AppMap name of the component in the Window.
    ****************/
    public DotNetMenu(String winname, String compname) {

        this(new Window(winname), compname);
    }

    protected DotNetMenu(String compname) {

        super(compname);
    }



    /*********** <pre> 
                 Action to select a menuItem according to its text value.
              
                 In RRAFS, this command will work on both JavaMenu items and 
                 JavaPopupMenu items.
				 For RJ implementation: When Field5 is provided,
									the routine first verifies that the specified menuitem exists and exits with error if it does not. 
									If it does exist then the select found menuitem. 
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param textValue  Optional:YES 
                 Case-insensitive text of menuItem to select OR an App Map reference.
              
     **********/
    public ComponentFunction selectMenuItem(String textValue ) {

        return DotNetMenuFunctions.selectMenuItem(getWindow().getName(), getName(), textValue);
    }

    /*********** <pre> 
                 Action to select a menuItem according to its text value.
              
                 In RRAFS, this command will work on both JavaMenu items and 
                 JavaPopupMenu items.
				 For RJ implementation: When Field5 is provided,
									the routine first verifies that the specified menuitem exists and exits with error if it does not. 
									If it does exist then the select found menuitem. 
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param table  Optional:NO
            The table to add the record to.
     @param textValue  Optional:YES 
                 Case-insensitive text of menuItem to select OR an App Map reference.
              
     **********/
    public void selectMenuItem(StepTestTable table, String textValue ) {

        if ( table == null ) throw new IllegalArgumentException ( "selectMenuItem.table = null");

        table.add( DotNetMenuFunctions.selectMenuItem(getWindow().getName(), getName(), textValue));
    }

    /*********** <pre> 
                 Action to select a menuItem according to a partial match of its text value.
              
                 In RRAFS, this command will work on both JavaMenu items and 
                 JavaPopupMenu items.
				 For RJ implementation: When Field5 is provided,
									the routine first verifies that the specified menuitem exists and exits with error if it does not. 
									If it does exist then the select found menuitem. 
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param textValue  Optional:YES 
                 Case-insensitive substring of menuItem to select OR an App Map reference.
              
     **********/
    public ComponentFunction selectMenuItemContains(String textValue ) {

        return DotNetMenuFunctions.selectMenuItemContains(getWindow().getName(), getName(), textValue);
    }

    /*********** <pre> 
                 Action to select a menuItem according to a partial match of its text value.
              
                 In RRAFS, this command will work on both JavaMenu items and 
                 JavaPopupMenu items.
				 For RJ implementation: When Field5 is provided,
									the routine first verifies that the specified menuitem exists and exits with error if it does not. 
									If it does exist then the select found menuitem. 
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param table  Optional:NO
            The table to add the record to.
     @param textValue  Optional:YES 
                 Case-insensitive substring of menuItem to select OR an App Map reference.
              
     **********/
    public void selectMenuItemContains(StepTestTable table, String textValue ) {

        if ( table == null ) throw new IllegalArgumentException ( "selectMenuItemContains.table = null");

        table.add( DotNetMenuFunctions.selectMenuItemContains(getWindow().getName(), getName(), textValue));
    }

    /*********** <pre> 
               Attempts to verify the a particular menuitem exists in a menu.
               
                The menuitem should be specified in the form 
                "Menu->Menu->MenuItem   CTRL+V" with the full text (ampersands optional), 
                spaces(if any), and keyboard shortcut text (if any).  
                (The ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItem command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItem command.
                
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param menuItemText  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              
     @param expectedStatus  Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
     **********/
    public ComponentFunction verifyMenuItem(String menuItemText, String expectedStatus ) {

        if ( menuItemText == null ) throw new IllegalArgumentException ( "verifyMenuItem.menuItemText = null");
        return DotNetMenuFunctions.verifyMenuItem(getWindow().getName(), getName(), menuItemText, expectedStatus);
    }

    /*********** <pre> 
               Attempts to verify the a particular menuitem exists in a menu.
               
                The menuitem should be specified in the form 
                "Menu->Menu->MenuItem   CTRL+V" with the full text (ampersands optional), 
                spaces(if any), and keyboard shortcut text (if any).  
                (The ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItem command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItem command.
                
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param table  Optional:NO
            The table to add the record to.
     @param menuItemText  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              
     @param expectedStatus  Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
     **********/
    public void verifyMenuItem(StepTestTable table, String menuItemText, String expectedStatus ) {

        if ( table == null ) throw new IllegalArgumentException ( "verifyMenuItem.table = null");

        if ( menuItemText == null ) throw new IllegalArgumentException ( "verifyMenuItem.menuItemText = null");
        table.add( DotNetMenuFunctions.verifyMenuItem(getWindow().getName(), getName(), menuItemText, expectedStatus));
    }

    /*********** <pre> 
               Attempts to verify the a particular menuitem exists in a menu.
               
                The menuitem should be specified in the form 
                "Menu->Menu->MenuItem   CTRL+V" with the full text (ampersands optional), 
                spaces(if any), and keyboard shortcut text (if any).  
                (The ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItem command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItem command.
                
                  </pre>    
    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>         menuItemText -- Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              <BR/>         expectedStatus -- Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
    </UL>

     **********/
    public ComponentFunction verifyMenuItem(String[] parameters ) {

        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuItem.parameters = null");
        return DotNetMenuFunctions.verifyMenuItem(getWindow().getName(), getName(), parameters);
    }

    /*********** <pre> 
               Attempts to verify the a particular menuitem exists in a menu.
               
                The menuitem should be specified in the form 
                "Menu->Menu->MenuItem   CTRL+V" with the full text (ampersands optional), 
                spaces(if any), and keyboard shortcut text (if any).  
                (The ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItem command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItem command.
                
                  </pre>    
    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param table  Optional:NO
            The table to add the record to.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>         menuItemText -- Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              <BR/>         expectedStatus -- Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
    </UL>

     **********/
    public void verifyMenuItem(StepTestTable table, String[] parameters ) {

        if ( table == null ) throw new IllegalArgumentException ( "verifyMenuItem.table = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuItem.parameters = null");
        table.add( DotNetMenuFunctions.verifyMenuItem(getWindow().getName(), getName(), parameters));
    }

    /*********** <pre> 
               Attempts to verify the existence of a menuitem found by partial text match.
               
                Attempts to verify the existence of a menuitem found by partial text match.
                The menuitem should be specified in the form "Menu->Menu->MenuItem".  
                (Optional ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItemContains command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItemContains command.
                
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param menuItemText  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              
     @param expectedStatus  Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
     **********/
    public ComponentFunction verifyMenuItemContains(String menuItemText, String expectedStatus ) {

        if ( menuItemText == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.menuItemText = null");
        return DotNetMenuFunctions.verifyMenuItemContains(getWindow().getName(), getName(), menuItemText, expectedStatus);
    }

    /*********** <pre> 
               Attempts to verify the existence of a menuitem found by partial text match.
               
                Attempts to verify the existence of a menuitem found by partial text match.
                The menuitem should be specified in the form "Menu->Menu->MenuItem".  
                (Optional ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItemContains command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItemContains command.
                
                  </pre>    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param table  Optional:NO
            The table to add the record to.
     @param menuItemText  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              
     @param expectedStatus  Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
     **********/
    public void verifyMenuItemContains(StepTestTable table, String menuItemText, String expectedStatus ) {

        if ( table == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.table = null");

        if ( menuItemText == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.menuItemText = null");
        table.add( DotNetMenuFunctions.verifyMenuItemContains(getWindow().getName(), getName(), menuItemText, expectedStatus));
    }

    /*********** <pre> 
               Attempts to verify the existence of a menuitem found by partial text match.
               
                Attempts to verify the existence of a menuitem found by partial text match.
                The menuitem should be specified in the form "Menu->Menu->MenuItem".  
                (Optional ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItemContains command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItemContains command.
                
                  </pre>    
    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>         menuItemText -- Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              <BR/>         expectedStatus -- Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
    </UL>

     **********/
    public ComponentFunction verifyMenuItemContains(String[] parameters ) {

        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.parameters = null");
        return DotNetMenuFunctions.verifyMenuItemContains(getWindow().getName(), getName(), parameters);
    }

    /*********** <pre> 
               Attempts to verify the existence of a menuitem found by partial text match.
               
                Attempts to verify the existence of a menuitem found by partial text match.
                The menuitem should be specified in the form "Menu->Menu->MenuItem".  
                (Optional ampersands precede any character in the menuitem that is underlined.)
                
                This command differs from the WindowFunction.VerifyMenuItemContains command because 
                here we are actually seeking a JavaMenu component, not a Window that contains 
                a menu.  Also, we do not currently verify any state information like the 
                WindowFunctions.VerifyMenuItemContains command.
                
                  </pre>    
    Supporting Engines:
    <P/><UL>
    <LI>Rational RobotJ</LI>
    </UL>

     @param table  Optional:NO
            The table to add the record to.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>         menuItemText -- Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to find.
              <BR/>         expectedStatus -- Optional:YES 
                Expected status string (or part thereof) of the menuitem. 
              
    </UL>

     **********/
    public void verifyMenuItemContains(StepTestTable table, String[] parameters ) {

        if ( table == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.table = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.parameters = null");
        table.add( DotNetMenuFunctions.verifyMenuItemContains(getWindow().getName(), getName(), parameters));
    }

}
