
/******************************************************************************
 * FlexNumericStepperFunctions.java
 *
 * Copyright (c) by SAS Institute Inc., Cary, NC 27513
 * General Public License: http://www.opensource.org/licenses/gpl-license.php
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * This file is automatically generated from XML source.  Any changes you make 
 * here will be erased the next time the file is generated.
 *
 * The following assets are needed to generate this file:
 *
 *   FlexNumericStepperFunctions.xml
 *   keyword_library.dtd
 *   XSLJavaCommonFunctions.xsl
 *   XSLJavaCommandModel.xsl
 *
 * Example invocation to generate:
 *
 *   msxsl.exe FlexNumericStepperFunctions.xml XSLJavaCommandModel.xsl -o FlexNumericStepperFunctions.java
 *
 ******************************************************************************/ 
package org.safs.model.commands;


import org.safs.model.ComponentFunction;


public class FlexNumericStepperFunctions {

    /*****************
    Private Singleton Instance
    ****************/
    private static final FlexNumericStepperFunctions singleton = new FlexNumericStepperFunctions(); 

    /*****************
    Private Constructor
    Static class needing no instantiation.
    ****************/
    private FlexNumericStepperFunctions() {}

    /*****************
    public Singleton to access class static methods via instance
    ****************/
    public static FlexNumericStepperFunctions getInstance() { return singleton;}

    /** "SetValue" */
    static public final String SETVALUE_KEYWORD = "SetValue";


    /*********** <pre> 
                 Action to set the value of the stepper according to its StepperValue. Currently, this component function is for Flex NumericStepper only.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational RobotJ</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param stepperValue  Optional:NO 
                 The value of the stepper to set.
              
     **********/
    static public ComponentFunction setValue (String winname, String compname, String stepperValue) {

        if ( winname == null ) throw new IllegalArgumentException ( "setValue.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "setValue.compname = null");

        if ( stepperValue == null ) throw new IllegalArgumentException ( "setValue.stepperValue = null");
        ComponentFunction cf = new ComponentFunction(SETVALUE_KEYWORD, winname, compname);
        cf.addParameter(stepperValue);
        return cf;
    }


}
