
/******************************************************************************
 * HTMLDocumentFunctions.java
 *
 * Copyright (C) SAS Institute, All rights reserved.
 * General Public License: https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * This file is automatically generated from XML source.  Any changes you make 
 * here will be erased the next time the file is generated.
 *
 * The following assets are needed to generate this file:
 *
 *   HTMLDocumentFunctions.xml
 *   keyword_library.dtd
 *   XSLJavaCommonFunctions.xsl
 *   XSLJavaCommandModel.xsl
 *
 * Example invocation to generate:
 *
 *   msxsl.exe HTMLDocumentFunctions.xml XSLJavaCommandModel.xsl -o HTMLDocumentFunctions.java
 *
 ******************************************************************************/ 
package org.safs.model.commands;


import org.safs.model.ComponentFunction;


public class HTMLDocumentFunctions {

    /*****************
    Private Singleton Instance
    ****************/
    private static final HTMLDocumentFunctions singleton = new HTMLDocumentFunctions(); 

    /*****************
    Private Constructor
    Static class needing no instantiation.
    ****************/
    private HTMLDocumentFunctions() {}

    /*****************
    public Singleton to access class static methods via instance
    ****************/
    public static HTMLDocumentFunctions getInstance() { return singleton;}

    /** "CaptureBodySourceToFile" */
    static public final String CAPTUREBODYSOURCETOFILE_KEYWORD = "CaptureBodySourceToFile";
    /** "CaptureBodyTextToFile" */
    static public final String CAPTUREBODYTEXTTOFILE_KEYWORD = "CaptureBodyTextToFile";
    /** "ClickLink" */
    static public final String CLICKLINK_KEYWORD = "ClickLink";
    /** "ClickLinkBeginning" */
    static public final String CLICKLINKBEGINNING_KEYWORD = "ClickLinkBeginning";
    /** "ClickLinkContaining" */
    static public final String CLICKLINKCONTAINING_KEYWORD = "ClickLinkContaining";
    /** "ClickLinkMatching" */
    static public final String CLICKLINKMATCHING_KEYWORD = "ClickLinkMatching";
    /** "VerifyBodySource" */
    static public final String VERIFYBODYSOURCE_KEYWORD = "VerifyBodySource";
    /** "VerifyBodyText" */
    static public final String VERIFYBODYTEXT_KEYWORD = "VerifyBodyText";


    /*********** <pre> 
                 Captures the HTML source of the BODY tag into a file.
               
                Captures the HTML source of the BODY tag into a file.
                This includes the BODY tag itself, everything inside it, and the closing 
                /Body tag as well.
                RobotJ (RJ) Specific Notes:
                	1) If your HTML document or browser does not support the 'outerHTML' property 
                	then you may have to resort to providing internet connection info in the properties 
                	file mentioned in #2.
                	
               		2) If you use proxy to connect to internet, proxy.server and proxy.server.port
               		in the file org.safs.rational.proxyParameter.properties must be set to ensure
               		the execution of this command.
                
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param filename  Optional:NO 
                Name of the output file to create in the active "Test" directory.
              
     @param fileEncoding  Optional:YES  DefaultVal:
             Specify a character encoding to be used when saving data to a file.
			 If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
     **********/
    static public ComponentFunction captureBodySourceToFile (String winname, String compname, String filename, String fileEncoding) {

        if ( winname == null ) throw new IllegalArgumentException ( "captureBodySourceToFile.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "captureBodySourceToFile.compname = null");

        if ( filename == null ) throw new IllegalArgumentException ( "captureBodySourceToFile.filename = null");
        ComponentFunction cf = new ComponentFunction(CAPTUREBODYSOURCETOFILE_KEYWORD, winname, compname);
        cf.addParameter(filename);
        cf.addParameter(fileEncoding);
        return cf;
    }


    /*********** <pre> 
                 Captures the HTML source of the BODY tag into a file.
               
                Captures the HTML source of the BODY tag into a file.
                This includes the BODY tag itself, everything inside it, and the closing 
                /Body tag as well.
                RobotJ (RJ) Specific Notes:
                	1) If your HTML document or browser does not support the 'outerHTML' property 
                	then you may have to resort to providing internet connection info in the properties 
                	file mentioned in #2.
                	
               		2) If you use proxy to connect to internet, proxy.server and proxy.server.port
               		in the file org.safs.rational.proxyParameter.properties must be set to ensure
               		the execution of this command.
                
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        filename -- Optional:NO 
                Name of the output file to create in the active "Test" directory.
              <BR/>        fileEncoding -- Optional:YES  DefaultVal:
             Specify a character encoding to be used when saving data to a file.
			 If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
    </UL>

     **********/
    static public ComponentFunction captureBodySourceToFile(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "captureBodySourceToFile.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "captureBodySourceToFile.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "captureBodySourceToFile.parameters = null");
        ComponentFunction cf = new ComponentFunction(CAPTUREBODYSOURCETOFILE_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Captures the visible document text into a file.
               
                Captures the visible document text into a file.
                That is, generally, the text you see with no HTML tags.
                /Body tag as well.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param filename  Optional:NO 
                Name of the output file to create in the active "Test" directory.
              
     @param fileEncoding  Optional:YES  DefaultVal:
             Specify a character encoding to be used when saving data to a file.
			 If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
     **********/
    static public ComponentFunction captureBodyTextToFile (String winname, String compname, String filename, String fileEncoding) {

        if ( winname == null ) throw new IllegalArgumentException ( "captureBodyTextToFile.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "captureBodyTextToFile.compname = null");

        if ( filename == null ) throw new IllegalArgumentException ( "captureBodyTextToFile.filename = null");
        ComponentFunction cf = new ComponentFunction(CAPTUREBODYTEXTTOFILE_KEYWORD, winname, compname);
        cf.addParameter(filename);
        cf.addParameter(fileEncoding);
        return cf;
    }


    /*********** <pre> 
                 Captures the visible document text into a file.
               
                Captures the visible document text into a file.
                That is, generally, the text you see with no HTML tags.
                /Body tag as well.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        filename -- Optional:NO 
                Name of the output file to create in the active "Test" directory.
              <BR/>        fileEncoding -- Optional:YES  DefaultVal:
             Specify a character encoding to be used when saving data to a file.
			 If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
    </UL>

     **********/
    static public ComponentFunction captureBodyTextToFile(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "captureBodyTextToFile.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "captureBodyTextToFile.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "captureBodyTextToFile.parameters = null");
        ComponentFunction cf = new ComponentFunction(CAPTUREBODYTEXTTOFILE_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Performs an HTMLLink Click based on a complete match of text found on 
                 Links within this HTMLDOCUMENT object.
               
                Performs an HTMLLink Click based on a complete match of text found on 
                Links within this HTMLDOCUMENT object.
                
                Optionally, the user can also specify a match index to indicate that 
                the desired Link is the "nth" Link that matches the text criteria.
                
                The text comparison for the Link is NOT case-sensitive by default.
                
                Leading and trailing whitespace will be removed from the links as they 
                are compared unless the link in the HTML itself is quoted.
                In addition, any Line Feeds and Carriage Returns will be removed.
                For the link, we use the outerText property to locate the text.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param compareTextValue  Optional:NO 
                The text to compare with each Link.
              
     @param matchIndex  Optional:YES
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              
     @param caseSensitive  Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
     **********/
    static public ComponentFunction clickLink (String winname, String compname, String compareTextValue, String matchIndex, String caseSensitive) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLink.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLink.compname = null");

        if ( compareTextValue == null ) throw new IllegalArgumentException ( "clickLink.compareTextValue = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINK_KEYWORD, winname, compname);
        cf.addParameter(compareTextValue);
        cf.addParameter(matchIndex);
        cf.addParameter(caseSensitive);
        return cf;
    }


    /*********** <pre> 
                 Performs an HTMLLink Click based on a complete match of text found on 
                 Links within this HTMLDOCUMENT object.
               
                Performs an HTMLLink Click based on a complete match of text found on 
                Links within this HTMLDOCUMENT object.
                
                Optionally, the user can also specify a match index to indicate that 
                the desired Link is the "nth" Link that matches the text criteria.
                
                The text comparison for the Link is NOT case-sensitive by default.
                
                Leading and trailing whitespace will be removed from the links as they 
                are compared unless the link in the HTML itself is quoted.
                In addition, any Line Feeds and Carriage Returns will be removed.
                For the link, we use the outerText property to locate the text.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        compareTextValue -- Optional:NO 
                The text to compare with each Link.
              <BR/>        matchIndex -- Optional:YES
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              <BR/>        caseSensitive -- Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
    </UL>

     **********/
    static public ComponentFunction clickLink(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLink.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLink.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "clickLink.parameters = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINK_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Performs an HTMLLink Click based on a partial match of text found on 
                 Links within this HTMLDOCUMENT object.
               
                Performs an HTMLLink Click based on a partial match of text found on 
                Links within this HTMLDOCUMENT object.  The text of the Link is 
                expected to BEGIN with the text provided by the user.  Optionally, 
                the user can also specify a match index to indicate that the desired 
                Link is the "nth" Link that matches the text criteria.
                
                The text comparison for the Link is NOT case-sensitive by default.  The 
                user can specify a case-senstive comparison via CaseSensitive Field #7. 
                
                Leading and trailing whitespace will be removed from the links as they 
                are compared unless the link in the HTML itself is quoted.
                In addition, any Line Feeds and Carriage Returns will be removed.
                For the link, we use the outerText property to locate the text.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param beginningTextValue  Optional:NO 
                The text (NOT case-sensitive) to compare with the beginning of each Link.
              
     @param matchIndex  Optional:YES 
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              
     @param caseSensitive  Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
     **********/
    static public ComponentFunction clickLinkBeginning (String winname, String compname, String beginningTextValue, String matchIndex, String caseSensitive) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLinkBeginning.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLinkBeginning.compname = null");

        if ( beginningTextValue == null ) throw new IllegalArgumentException ( "clickLinkBeginning.beginningTextValue = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINKBEGINNING_KEYWORD, winname, compname);
        cf.addParameter(beginningTextValue);
        cf.addParameter(matchIndex);
        cf.addParameter(caseSensitive);
        return cf;
    }


    /*********** <pre> 
                 Performs an HTMLLink Click based on a partial match of text found on 
                 Links within this HTMLDOCUMENT object.
               
                Performs an HTMLLink Click based on a partial match of text found on 
                Links within this HTMLDOCUMENT object.  The text of the Link is 
                expected to BEGIN with the text provided by the user.  Optionally, 
                the user can also specify a match index to indicate that the desired 
                Link is the "nth" Link that matches the text criteria.
                
                The text comparison for the Link is NOT case-sensitive by default.  The 
                user can specify a case-senstive comparison via CaseSensitive Field #7. 
                
                Leading and trailing whitespace will be removed from the links as they 
                are compared unless the link in the HTML itself is quoted.
                In addition, any Line Feeds and Carriage Returns will be removed.
                For the link, we use the outerText property to locate the text.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        beginningTextValue -- Optional:NO 
                The text (NOT case-sensitive) to compare with the beginning of each Link.
              <BR/>        matchIndex -- Optional:YES 
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              <BR/>        caseSensitive -- Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
    </UL>

     **********/
    static public ComponentFunction clickLinkBeginning(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLinkBeginning.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLinkBeginning.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "clickLinkBeginning.parameters = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINKBEGINNING_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Performs an HTMLLink Click based on a partial match of text found on 
                 Links within this HTMLDOCUMENT object.
               
                Performs an HTMLLink Click based on a partial match of text found on 
                Links within this HTMLDOCUMENT object.  The text of the Link is 
                expected to CONTAIN the text provided by the user at any position in 
                the Link text--not strictly the beginning as in ClickLinkBeginning.
                
                Optionally, the user can also specify a match index to indicate that 
                the desired Link is the "nth" Link that matches the text criteria.
                
                The text comparison for the Link is NOT case-sensitive by default.
                
                Leading and trailing whitespace will be removed from the links as they 
                are compared unless the link in the HTML itself is quoted.
                In addition, any Line Feeds and Carriage Returns will be removed.
                For the link, we use the outerText property to locate the text.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param compareTextValue  Optional:NO 
                The text to compare with each Link.
              
     @param matchIndex  Optional:YES
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              
     @param caseSensitive  Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
     **********/
    static public ComponentFunction clickLinkContaining (String winname, String compname, String compareTextValue, String matchIndex, String caseSensitive) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLinkContaining.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLinkContaining.compname = null");

        if ( compareTextValue == null ) throw new IllegalArgumentException ( "clickLinkContaining.compareTextValue = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINKCONTAINING_KEYWORD, winname, compname);
        cf.addParameter(compareTextValue);
        cf.addParameter(matchIndex);
        cf.addParameter(caseSensitive);
        return cf;
    }


    /*********** <pre> 
                 Performs an HTMLLink Click based on a partial match of text found on 
                 Links within this HTMLDOCUMENT object.
               
                Performs an HTMLLink Click based on a partial match of text found on 
                Links within this HTMLDOCUMENT object.  The text of the Link is 
                expected to CONTAIN the text provided by the user at any position in 
                the Link text--not strictly the beginning as in ClickLinkBeginning.
                
                Optionally, the user can also specify a match index to indicate that 
                the desired Link is the "nth" Link that matches the text criteria.
                
                The text comparison for the Link is NOT case-sensitive by default.
                
                Leading and trailing whitespace will be removed from the links as they 
                are compared unless the link in the HTML itself is quoted.
                In addition, any Line Feeds and Carriage Returns will be removed.
                For the link, we use the outerText property to locate the text.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        compareTextValue -- Optional:NO 
                The text to compare with each Link.
              <BR/>        matchIndex -- Optional:YES
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              <BR/>        caseSensitive -- Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
    </UL>

     **********/
    static public ComponentFunction clickLinkContaining(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLinkContaining.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLinkContaining.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "clickLinkContaining.parameters = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINKCONTAINING_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 DEPARECATED.  This command is identical to ClickLink.
               
                 DEPARECATED.  This command is identical to ClickLink.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param compareTextValue  Optional:NO 
                The text to compare with each Link.
              
     @param matchIndex  Optional:YES
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              
     @param caseSensitive  Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
     **********/
    static public ComponentFunction clickLinkMatching (String winname, String compname, String compareTextValue, String matchIndex, String caseSensitive) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLinkMatching.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLinkMatching.compname = null");

        if ( compareTextValue == null ) throw new IllegalArgumentException ( "clickLinkMatching.compareTextValue = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINKMATCHING_KEYWORD, winname, compname);
        cf.addParameter(compareTextValue);
        cf.addParameter(matchIndex);
        cf.addParameter(caseSensitive);
        return cf;
    }


    /*********** <pre> 
                 DEPARECATED.  This command is identical to ClickLink.
               
                 DEPARECATED.  This command is identical to ClickLink.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        compareTextValue -- Optional:NO 
                The text to compare with each Link.
              <BR/>        matchIndex -- Optional:YES
                Optional match index indicating the desired link is not the first
                link that matches, but the "nth" link that matches.
              <BR/>        caseSensitive -- Optional:YES
                "Case-Sensitive", "CaseSensitive", or "True" will make search case-sensitive.
              
    </UL>

     **********/
    static public ComponentFunction clickLinkMatching(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "clickLinkMatching.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "clickLinkMatching.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "clickLinkMatching.parameters = null");
        ComponentFunction cf = new ComponentFunction(CLICKLINKMATCHING_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Compares the HTML source of the BODY tag with that of a benchmark file.
               
                This includes the BODY tag itself, everything inside it, and the closing 
                /Body tag as well.
                
                RRAFS:
                The routine will automatically create a temporary ObjectData VP with a 
                dummy baseline, capture the actual file, transfer it to active "Test" 
                directory, and compare it with the benchmark.  The routine will then 
                delete all significant remnants of the temporary ObjectData VP.
                 
                RRAFS:
                This routine requires that the following two files exist in the 
                DDE_RUNTIME directory:
                 
                HTMLDocumentHTML.grd
                HTMLDocumentHTML.vpm
                
             The command may produce a WARNING if a diff tool for which we 
             have no means to verify the results is configured for use.  
             Consequently, if these warnings are expected, the user can use the 
             "TW" test record type to avoid issuing these warnings.
			   RobotJ (RJ) Specific Notes:
               		1) If you use proxy to connect to internet, proxy.server and proxy.server.port
               		in the file org.safs.rational.proxyParameter.properties must be set to ensure
               		the execution of this command.
                
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param benchmark  Optional:NO 
                Name of the benchmark file in the active "Bench" directory to 
                use for the actual test file comparison.
              
     @param fileEncoding  Optional:YES  DefaultVal:
             Specify a character encoding to be used when opening a bench file.
             If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
     **********/
    static public ComponentFunction verifyBodySource (String winname, String compname, String benchmark, String fileEncoding) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyBodySource.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyBodySource.compname = null");

        if ( benchmark == null ) throw new IllegalArgumentException ( "verifyBodySource.benchmark = null");
        ComponentFunction cf = new ComponentFunction(VERIFYBODYSOURCE_KEYWORD, winname, compname);
        cf.addParameter(benchmark);
        cf.addParameter(fileEncoding);
        return cf;
    }


    /*********** <pre> 
                 Compares the HTML source of the BODY tag with that of a benchmark file.
               
                This includes the BODY tag itself, everything inside it, and the closing 
                /Body tag as well.
                
                RRAFS:
                The routine will automatically create a temporary ObjectData VP with a 
                dummy baseline, capture the actual file, transfer it to active "Test" 
                directory, and compare it with the benchmark.  The routine will then 
                delete all significant remnants of the temporary ObjectData VP.
                 
                RRAFS:
                This routine requires that the following two files exist in the 
                DDE_RUNTIME directory:
                 
                HTMLDocumentHTML.grd
                HTMLDocumentHTML.vpm
                
             The command may produce a WARNING if a diff tool for which we 
             have no means to verify the results is configured for use.  
             Consequently, if these warnings are expected, the user can use the 
             "TW" test record type to avoid issuing these warnings.
			   RobotJ (RJ) Specific Notes:
               		1) If you use proxy to connect to internet, proxy.server and proxy.server.port
               		in the file org.safs.rational.proxyParameter.properties must be set to ensure
               		the execution of this command.
                
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        benchmark -- Optional:NO 
                Name of the benchmark file in the active "Bench" directory to 
                use for the actual test file comparison.
              <BR/>        fileEncoding -- Optional:YES  DefaultVal:
             Specify a character encoding to be used when opening a bench file.
             If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
    </UL>

     **********/
    static public ComponentFunction verifyBodySource(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyBodySource.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyBodySource.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyBodySource.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYBODYSOURCE_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Compares the visible doc text with that of a benchmark file.
               
                The routine will automatically create a temporary ObjectData VP with a 
                dummy baseline, capture the actual file, transfer it to active "Test" 
                directory, and compare it with the benchmark.  The routine will then 
                delete all significant remnants of the temporary ObjectData VP.
                 
                This routine requires that the following two files exist in the 
                DDE_RUNTIME directory:
                 
                HTMLDocumentText.grd
                HTMLDocumentText.vpm
                
             The command may produce a WARNING if a diff tool for which we 
             have no means to verify the results is configured for use.  
             Consequently, if these warnings are expected, the user can use the 
             "TW" test record type to avoid issuing these warnings.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param benchmark  Optional:NO 
                Name of the benchmark file in the active "Bench" directory to 
                use for the actual test file comparison.
              
     @param fileEncoding  Optional:YES  DefaultVal:
             Specify a character encoding to be used when opening a bench file.
             If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
     **********/
    static public ComponentFunction verifyBodyText (String winname, String compname, String benchmark, String fileEncoding) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyBodyText.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyBodyText.compname = null");

        if ( benchmark == null ) throw new IllegalArgumentException ( "verifyBodyText.benchmark = null");
        ComponentFunction cf = new ComponentFunction(VERIFYBODYTEXT_KEYWORD, winname, compname);
        cf.addParameter(benchmark);
        cf.addParameter(fileEncoding);
        return cf;
    }


    /*********** <pre> 
                 Compares the visible doc text with that of a benchmark file.
               
                The routine will automatically create a temporary ObjectData VP with a 
                dummy baseline, capture the actual file, transfer it to active "Test" 
                directory, and compare it with the benchmark.  The routine will then 
                delete all significant remnants of the temporary ObjectData VP.
                 
                This routine requires that the following two files exist in the 
                DDE_RUNTIME directory:
                 
                HTMLDocumentText.grd
                HTMLDocumentText.vpm
                
             The command may produce a WARNING if a diff tool for which we 
             have no means to verify the results is configured for use.  
             Consequently, if these warnings are expected, the user can use the 
             "TW" test record type to avoid issuing these warnings.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        benchmark -- Optional:NO 
                Name of the benchmark file in the active "Bench" directory to 
                use for the actual test file comparison.
              <BR/>        fileEncoding -- Optional:YES  DefaultVal:
             Specify a character encoding to be used when opening a bench file.
             If it is not specified, the system default file encoding will be used.
             The encoding should be a valid string supported by Java; if it is not valid,
             the system default file encoding will be used instead.
            
    </UL>

     **********/
    static public ComponentFunction verifyBodyText(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyBodyText.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyBodyText.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyBodyText.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYBODYTEXT_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


}
