
/******************************************************************************
 * WindowFunctions.java
 *
 * Copyright (c) by SAS Institute Inc., Cary, NC 27513
 * General Public License: http://www.opensource.org/licenses/gpl-license.php
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * This file is automatically generated from XML source.  Any changes you make 
 * here will be erased the next time the file is generated.
 *
 * The following assets are needed to generate this file:
 *
 *   WindowFunctions.xml
 *   keyword_library.dtd
 *   XSLJavaCommonFunctions.xsl
 *   XSLJavaCommandModel.xsl
 *
 * Example invocation to generate:
 *
 *   msxsl.exe WindowFunctions.xml XSLJavaCommandModel.xsl -o WindowFunctions.java
 *
 ******************************************************************************/ 
package org.safs.model.commands;


import org.safs.model.ComponentFunction;


public class WindowFunctions {

    /*****************
    Private Singleton Instance
    ****************/
    private static final WindowFunctions singleton = new WindowFunctions(); 

    /*****************
    Private Constructor
    Static class needing no instantiation.
    ****************/
    private WindowFunctions() {}

    /*****************
    public Singleton to access class static methods via instance
    ****************/
    public static WindowFunctions getInstance() { return singleton;}

    /** "Click" */
    static public final String CLICK_KEYWORD = "Click";
    /** "CloseWindow" */
    static public final String CLOSEWINDOW_KEYWORD = "CloseWindow";
    /** "FocusWindow" */
    static public final String SETFOCUS_KEYWORD = "SetFocus";
    /** "CompareStoredProperties" */
    static public final String COMPARESTOREDPROPERTIES_KEYWORD = "CompareStoredProperties";
    /** "DoubleClick" */
    static public final String DOUBLECLICK_KEYWORD = "DoubleClick";
    /** "GetWinInfo" */
    static public final String GETWININFO_KEYWORD = "GetWinInfo";
    /** "GoBack" */
    static public final String GOBACK_KEYWORD = "GoBack";
    /** "InputCharacters" */
    static public final String INPUTCHARACTERS_KEYWORD = "InputCharacters";
    /** "InputKeys" */
    static public final String INPUTKEYS_KEYWORD = "InputKeys";
    /** "Maximize" */
    static public final String MAXIMIZE_KEYWORD = "Maximize";
    /** "Minimize" */
    static public final String MINIMIZE_KEYWORD = "Minimize";
    /** "PinchClose" */
    static public final String PINCHCLOSE_KEYWORD = "PinchClose";
    /** "PinchOpen" */
    static public final String PINCHOPEN_KEYWORD = "PinchOpen";
    /** "Restore" */
    static public final String RESTORE_KEYWORD = "Restore";
    /** "RightClick" */
    static public final String RIGHTCLICK_KEYWORD = "RightClick";
    /** "SelectMenuID" */
    static public final String SELECTMENUID_KEYWORD = "SelectMenuID";
    /** "SelectMenuItem" */
    static public final String SELECTMENUITEM_KEYWORD = "SelectMenuItem";
    /** "SelectMenuItemContains" */
    static public final String SELECTMENUITEMCONTAINS_KEYWORD = "SelectMenuItemContains";
    /** "SetPosition" */
    static public final String SETPOSITION_KEYWORD = "SetPosition";
    /** "VerifyImage" */
    static public final String VERIFYIMAGE_KEYWORD = "VerifyImage";
    /** "VerifyMainMenu" */
    static public final String VERIFYMAINMENU_KEYWORD = "VerifyMainMenu";
    /** "VerifyMenuID" */
    static public final String VERIFYMENUID_KEYWORD = "VerifyMenuID";
    /** "VerifyMenuItem" */
    static public final String VERIFYMENUITEM_KEYWORD = "VerifyMenuItem";
    /** "VerifyMenuItemContains" */
    static public final String VERIFYMENUITEMCONTAINS_KEYWORD = "VerifyMenuItemContains";
    /** "VerifyOCRValue" */
    static public final String VERIFYOCRVALUE_KEYWORD = "VerifyOCRValue";


    /*********** <pre> 
                Performs a click on any part of a Window based on a stored x,y coordinate.
               
                For components that are unrecognized, like ActiveToolbar menuitems, 
                we can click on these or any part of a Window based on a stored x,y 
                coordinate.  The window containing the coordinate is first given 
                context and then a click is generated at the coordinate.  Thus, an item 
                or object can be referenced by name even though it is only recognized
                via coordinates.
                
                The coordinate lookup is done with the component name of the record AND 
                Field #5.
                
                Typical Data Table records:
                 
                (1) t MainWindow MainWindow Click AnObject
                (2) t MainWindow FileMenu  Click Exit
                
                #1 above will contain an AnObject="3,10" entry in the MainWindow section 
                of the Application Map to click at x=3, y=10 in the MainWindow.
                
                #2 above will contain a FileMenu entry in the MainWindow section with 
                normal recognition information for it (the type, however, should still 
                be "Window" even if unspecified).  FileMenu will also have it's
                own section in the Application Map in which there will be an entry like 
                Exit="15,30".  This will tell Robot to locate the FileMenu Window 
                object and click at the coordinates specified by the reference.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param appMapSubkey  Optional:NO 
                Name of the AppMap subkey to lookup and use for the click.
              
     **********/
    static public ComponentFunction click (String winname, String compname, String appMapSubkey) {

        if ( winname == null ) throw new IllegalArgumentException ( "click.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "click.compname = null");

        if ( appMapSubkey == null ) throw new IllegalArgumentException ( "click.appMapSubkey = null");
        ComponentFunction cf = new ComponentFunction(CLICK_KEYWORD, winname, compname);
        cf.addParameter(appMapSubkey);
        return cf;
    }


    /*********** <pre> 
                Sends a Close command to the active window.
               
	      
		
		   
			
			    
			
		   
		
		
                This Window command has a problem in that it does not want to
                use the same recognition methods used by the other Window commands (like
                SetContext).  Particularly, it does not accept the Type=Window portion
                of these recognition methods.  In addition, if the window is a child
                window of a parent then it expects the ";ChildWindow" add-on in the 
                recognition method.  The child may also need the parent as part of its
                full recognition string like:
                
                ChildWindow=Type=Window;<parent rec>;\;Caption=<caption>;ChildWindow
                
                To handle these child windows, we parse the typical recognition method for 
                our window and attempt to handle these issues.  Once SetContext has 
                successfully set our window, we then remove any "Type=Window" substring 
                if present and add the ";ChildWindow" substring if not present.
                
                To take advantage of this, this routine must be called with the child
                window as a component of the parent window like below:
                
                t, ParentWindow, ChildWindow, CloseWindow
                
                If the routine is called like either of the examples below then default
                processing will occur.  This will merely SetContext on the provided 
                Window and use "CurrentWindow" as the parameter to the command.
                
                t, ParentWindow, ParentWindow, CloseWindow
                t, ChildWindow , ChildWindow , CloseWindow  (normally won't work)
		
	      
	      
		
		    
			
			    
			
		    
		
		Closes the "current" or "lastUsed" WebDriver associated with the found Window component.
	      
                
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
        <LI>OpenQA Selenium</LI>
        <LI>OpenQA Selenium</LI>
        <LI>AutomatedQA TestComplete</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     **********/
    static public ComponentFunction closeWindow (String winname, String compname) {

        if ( winname == null ) throw new IllegalArgumentException ( "closeWindow.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "closeWindow.compname = null");

        ComponentFunction cf = new ComponentFunction(CLOSEWINDOW_KEYWORD, winname, compname);
        return cf;
    }


    /*********** <pre> 
                Performs a WindowVP CompareProperties on an object.  
               
                Performs a WindowVP CompareProperties on an object.  
                The benchmark VP must already exist and be an asset of the currently 
                running script.
                
                To make an existing VP an asset of the current script,
                the existing script, e.g.,
                
                MADHATTERScript.MyObjectVP.base.OBP
                
                can be copied and renamed to
                
                MyDDScript.MyObjectVP.base.OBP
                
                where MyDDScript is the name of the current script.
                
                The name of the actual VP, MyObjectVP, cannot be altered.
                
                Example 1: Perform a WindowVP on a given window
                
                t, MainWindow, MainWindow, CompareStoredProperties, MainSetupVP1
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param vPAsset  Optional:NO 
                 Name of the pre-existing VP asset stored in the currently running script.
              
     **********/
    static public ComponentFunction compareStoredProperties (String winname, String compname, String vPAsset) {

        if ( winname == null ) throw new IllegalArgumentException ( "compareStoredProperties.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "compareStoredProperties.compname = null");

        if ( vPAsset == null ) throw new IllegalArgumentException ( "compareStoredProperties.vPAsset = null");
        ComponentFunction cf = new ComponentFunction(COMPARESTOREDPROPERTIES_KEYWORD, winname, compname);
        cf.addParameter(vPAsset);
        return cf;
    }


    /*********** <pre> 
                Performs a double-click on any part of a Window based on a stored x,y coordinate.
               
                For components that are unrecognized, like ActiveToolbar menuitems, 
                we can double click on these or any part of a Window based on a stored 
                x,y coordinate.  The window containing the coordinate is first given 
                context and then a double click is generated at the coordinate.  Thus, 
                an item or object can be referenced by name even though it is only 
                recognized via coordinates.
                
                The coordinate lookup is done with the component name of the record AND 
                Field #5.
                 
                Typical Data Table records:
                
                (1) t MainWindow MainWindow DoubleClick AnObject
                (2) t MainWindow FolderTree DoubleClick Node1
                
                #1 above will contain an AnObject="3,10" entry in the MainWindow section 
                of the Application Map to double click at x=3, y=10 in the MainWindow.
                
                #2 above will contain a FolderTree entry in the MainWindow section with 
                normal recognition information for it .  FolderTree will also have it's
                own section in the Application Map in which there will be an entry like 
                Node1="15,30".  This will tell Robot to locate the FolderTree 
                object and double click at the coordinates specified by the reference.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param appMapSubkey  Optional:NO 
                Name of the AppMap subkey to lookup and use for the double-click.
              
     **********/
    static public ComponentFunction doubleClick (String winname, String compname, String appMapSubkey) {

        if ( winname == null ) throw new IllegalArgumentException ( "doubleClick.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "doubleClick.compname = null");

        if ( appMapSubkey == null ) throw new IllegalArgumentException ( "doubleClick.appMapSubkey = null");
        ComponentFunction cf = new ComponentFunction(DOUBLECLICK_KEYWORD, winname, compname);
        cf.addParameter(appMapSubkey);
        return cf;
    }


    /*********** <pre> 
                     Gets the value of any property in a window.
                    
                     Gets the value of any property in a window and assigns that property
                     to a variable for later use.
                     
                     
                       </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param propertyName  Optional:NO 
                     The name of the property to retrieve.
                   
     @param variableName  Optional:NO 
			  The name of the variable that the property value should be stored in.
			
     **********/
    static public ComponentFunction getWinInfo (String winname, String compname, String propertyName, String variableName) {

        if ( winname == null ) throw new IllegalArgumentException ( "getWinInfo.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "getWinInfo.compname = null");

        if ( propertyName == null ) throw new IllegalArgumentException ( "getWinInfo.propertyName = null");
        if ( variableName == null ) throw new IllegalArgumentException ( "getWinInfo.variableName = null");
        ComponentFunction cf = new ComponentFunction(GETWININFO_KEYWORD, winname, compname);
        cf.addParameter(propertyName);
        cf.addParameter(variableName);
        return cf;
    }


    /*********** <pre> 
                     Gets the value of any property in a window.
                    
                     Gets the value of any property in a window and assigns that property
                     to a variable for later use.
                     
                     
                       </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        propertyName -- Optional:NO 
                     The name of the property to retrieve.
                   <BR/>        variableName -- Optional:NO 
			  The name of the variable that the property value should be stored in.
			
    </UL>

     **********/
    static public ComponentFunction getWinInfo(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "getWinInfo.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "getWinInfo.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "getWinInfo.parameters = null");
        ComponentFunction cf = new ComponentFunction(GETWININFO_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                     Make the application\device "go back" to the previous state or window.
                    
                     This is largely for apps or devices--like mobile devices--that have the ability to 
                     "go back" that might be activated by a control that is NOT always part of 
                     the application GUI.  Example: a hardware "back" button or menu button that is not 
                     part of the application itself.
                     
                     Depending upon the technology implementation, The WINDOWNAME may not have to be 
                     valid or exist at the time of invocation.  That is, the WINDOWNAME and COMPNAME 
                     fields might not be used and can contain anything.                     
                     
                       </pre>    Supporting Engines:
    <P/><UL>
        <LI>Google Android</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     **********/
    static public ComponentFunction goBack (String winname, String compname) {

        if ( winname == null ) throw new IllegalArgumentException ( "goBack.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "goBack.compname = null");

        ComponentFunction cf = new ComponentFunction(GOBACK_KEYWORD, winname, compname);
        return cf;
    }


    /*********** <pre> 
                Sends literal text to the active window via an InputChars command.
               
                Sends literal text to the active window via an InputChars command.
                The InputChars command does not convert or interpret any special 
                characters like InputKeys (InputKeystrokes) does.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param textValue  Optional:NO 
                String of keystrokes to send.
              
     **********/
    static public ComponentFunction inputCharacters (String winname, String compname, String textValue) {

        if ( winname == null ) throw new IllegalArgumentException ( "inputCharacters.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "inputCharacters.compname = null");

        if ( textValue == null ) throw new IllegalArgumentException ( "inputCharacters.textValue = null");
        ComponentFunction cf = new ComponentFunction(INPUTCHARACTERS_KEYWORD, winname, compname);
        cf.addParameter(textValue);
        return cf;
    }


    /*********** <pre> 
                Sends keystrokes to the active window via an InputKeys command.
               
                Sends keystrokes to the active window via an InputKeys command.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param textValue  Optional:NO 
                String of keystrokes to send.
              
     **********/
    static public ComponentFunction inputKeys (String winname, String compname, String textValue) {

        if ( winname == null ) throw new IllegalArgumentException ( "inputKeys.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "inputKeys.compname = null");

        if ( textValue == null ) throw new IllegalArgumentException ( "inputKeys.textValue = null");
        ComponentFunction cf = new ComponentFunction(INPUTKEYS_KEYWORD, winname, compname);
        cf.addParameter(textValue);
        return cf;
    }


    /*********** <pre> 
                Sends a WMaximize command to the active window.
               
                Sends a WMaximize command to the active window.
                
                This Window command has a problem in that it does not want to
                use the same recognition methods used by the other Window commands (like
                SetContext).  Particularly, it does not accept the Type=Window portion
                of these recognition methods.  In addition, if the window is a child
                window of a parent then it expects the ";ChildWindow" add-on in the 
                recognition method.  The child may also need the parent as part of its
                full recognition string like:
                
                ChildWindow=Type=Window;<parent rec>;\;Caption=<caption>;ChildWindow
                 
                To handle these child windows, we parse the typical recognition method for 
                our window and attempt to handle these issues.  Once SetContext has 
                successfully set our window, we then remove any "Type=Window" substring 
                if present and add the ";ChildWindow" substring if not present.
                
                To take advantage of this, this routine must be called with the child
                window as a component of the parent window like below:
                
                t, ParentWindow, ChildWindow, Maximize
                
                If the routine is called like either of the examples below then default
                processing will occur.  This will merely SetContext on the provided 
                Window and use "CurrentWindow" as the parameter to the command.
                
                t, ParentWindow, ParentWindow, Maximize
                t, ChildWindow , ChildWindow , Maximize   (normally won't work)
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
        <LI>OpenQA Selenium</LI>
        <LI>AutomatedQA TestComplete</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     **********/
    static public ComponentFunction maximize (String winname, String compname) {

        if ( winname == null ) throw new IllegalArgumentException ( "maximize.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "maximize.compname = null");

        ComponentFunction cf = new ComponentFunction(MAXIMIZE_KEYWORD, winname, compname);
        return cf;
    }


    /*********** <pre> 
                Sends a WMinimize command to the active window.
               
                Sends a WMinimize command to the active window.
                
                This Window command has a problem in that it does not want to
                use the same recognition methods used by the other Window commands (like
                SetContext).  Particularly, it does not accept the Type=Window portion
                of these recognition methods.  In addition, if the window is a child
                window of a parent then it expects the ";ChildWindow" add-on in the 
                recognition method.  The child may also need the parent as part of its
                full recognition string like:
                
                ChildWindow=Type=Window;<parent rec>;\;Caption=<caption>;ChildWindow
                
                To handle these child windows, we parse the typical recognition method for 
                our window and attempt to handle these issues.  Once SetContext has 
                successfully set our window, we then remove any "Type=Window" substring 
                if present and add the ";ChildWindow" substring if not present.
                
                To take advantage of this, this routine must be called with the child
                window as a component of the parent window like below:
                
                t, ParentWindow, ChildWindow, Minimize
                
                If the routine is called like either of the examples below then default
                processing will occur.  This will merely SetContext on the provided 
                Window and use "CurrentWindow" as the parameter to the command.
                
                t, ParentWindow, ParentWindow, Minimize
                t, ChildWindow , ChildWindow , Minimize   (normally won't work)
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
        <LI>OpenQA Selenium</LI>
        <LI>AutomatedQA TestComplete</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     **********/
    static public ComponentFunction minimize (String winname, String compname) {

        if ( winname == null ) throw new IllegalArgumentException ( "minimize.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "minimize.compname = null");

        ComponentFunction cf = new ComponentFunction(MINIMIZE_KEYWORD, winname, compname);
        return cf;
    }


    /*********** <pre> 
                     Perform a shrinking "zoom out" operation on a touchscreen device supporting the feature.
                    
                     Perform a shrinking "zoom out" operation on a touchscreen device supporting the feature.
                     
                     Effectively shrinks a user-defined rectangular area on the screen.
                     
                     IOS expects the Window/Component to be the main active Window of the application.
                     
                       </pre>    Supporting Engines:
    <P/><UL>
        <LI>Apple IOS</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param originSubKey  Optional:NO 
                     The AppMapSubkey that contains the onscreen rectangle for the pinch operation.
                   
     @param resizeSubKey  Optional:NO 
                     Name of the AppMap subkey to lookup for the resize value or the literal text of 
                     the resize values.
                   
     @param duration  Optional:YES  DefaultVal:1The number of seconds to take for the operation.
     **********/
    static public ComponentFunction pinchClose (String winname, String compname, String originSubKey, String resizeSubKey, String duration) {

        if ( winname == null ) throw new IllegalArgumentException ( "pinchClose.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "pinchClose.compname = null");

        if ( originSubKey == null ) throw new IllegalArgumentException ( "pinchClose.originSubKey = null");
        if ( resizeSubKey == null ) throw new IllegalArgumentException ( "pinchClose.resizeSubKey = null");
        ComponentFunction cf = new ComponentFunction(PINCHCLOSE_KEYWORD, winname, compname);
        cf.addParameter(originSubKey);
        cf.addParameter(resizeSubKey);
        cf.addParameter(duration);
        return cf;
    }


    /*********** <pre> 
                     Perform a shrinking "zoom out" operation on a touchscreen device supporting the feature.
                    
                     Perform a shrinking "zoom out" operation on a touchscreen device supporting the feature.
                     
                     Effectively shrinks a user-defined rectangular area on the screen.
                     
                     IOS expects the Window/Component to be the main active Window of the application.
                     
                       </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Apple IOS</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        originSubKey -- Optional:NO 
                     The AppMapSubkey that contains the onscreen rectangle for the pinch operation.
                   <BR/>        resizeSubKey -- Optional:NO 
                     Name of the AppMap subkey to lookup for the resize value or the literal text of 
                     the resize values.
                   <BR/>        duration -- Optional:YES  DefaultVal:1The number of seconds to take for the operation.
    </UL>

     **********/
    static public ComponentFunction pinchClose(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "pinchClose.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "pinchClose.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "pinchClose.parameters = null");
        ComponentFunction cf = new ComponentFunction(PINCHCLOSE_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                     Perform an expanding "zoom in" operation on a touchscreen device supporting the feature.
                    
                     Perform an expanding "zoom in" operation on a touchscreen device supporting the feature.
                     
                     Effectively expands or stretches a user-defined rectangular area on the screen.
                     
                     IOS expects the Window/Component to be the main active Window of the application.
                     
                       </pre>    Supporting Engines:
    <P/><UL>
        <LI>Apple IOS</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param originSubKey  Optional:NO 
                     The AppMapSubkey that contains the onscreen rectangle for the pinch operation.
                   
     @param resizeSubKey  Optional:NO 
                     Name of the AppMap subkey to lookup for the resize value or the literal text of 
                     the resize values.
                   
     @param duration  Optional:YES  DefaultVal:1The number of seconds to take for the operation.
     **********/
    static public ComponentFunction pinchOpen (String winname, String compname, String originSubKey, String resizeSubKey, String duration) {

        if ( winname == null ) throw new IllegalArgumentException ( "pinchOpen.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "pinchOpen.compname = null");

        if ( originSubKey == null ) throw new IllegalArgumentException ( "pinchOpen.originSubKey = null");
        if ( resizeSubKey == null ) throw new IllegalArgumentException ( "pinchOpen.resizeSubKey = null");
        ComponentFunction cf = new ComponentFunction(PINCHOPEN_KEYWORD, winname, compname);
        cf.addParameter(originSubKey);
        cf.addParameter(resizeSubKey);
        cf.addParameter(duration);
        return cf;
    }


    /*********** <pre> 
                     Perform an expanding "zoom in" operation on a touchscreen device supporting the feature.
                    
                     Perform an expanding "zoom in" operation on a touchscreen device supporting the feature.
                     
                     Effectively expands or stretches a user-defined rectangular area on the screen.
                     
                     IOS expects the Window/Component to be the main active Window of the application.
                     
                       </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Apple IOS</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        originSubKey -- Optional:NO 
                     The AppMapSubkey that contains the onscreen rectangle for the pinch operation.
                   <BR/>        resizeSubKey -- Optional:NO 
                     Name of the AppMap subkey to lookup for the resize value or the literal text of 
                     the resize values.
                   <BR/>        duration -- Optional:YES  DefaultVal:1The number of seconds to take for the operation.
    </UL>

     **********/
    static public ComponentFunction pinchOpen(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "pinchOpen.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "pinchOpen.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "pinchOpen.parameters = null");
        ComponentFunction cf = new ComponentFunction(PINCHOPEN_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                Sends a RestorePos command to the active window.
               
                Sends a RestorePos command to the active window.
                
                This Window command has a problem in that it does not want to
                use the same recognition methods used by the other Window commands (like
                SetContext).  Particularly, it does not accept the Type=Window portion
                of these recognition methods.  In addition, if the window is a child
                window of a parent then it expects the ";ChildWindow" add-on in the 
                recognition method.  The child may also need the parent as part of its
                full recognition string like:
                
                ChildWindow=Type=Window;<parent rec>;\;Caption=<caption>;ChildWindow
                
                To handle these child windows, we parse the typical recognition method for 
                our window and attempt to handle these issues.  Once SetContext has 
                successfully set our window, we then remove any "Type=Window" substring 
                if present and add the ";ChildWindow" substring if not present.
                
                To take advantage of this, this routine must be called with the child
                window as a component of the parent window like below:
                
                t, ParentWindow, ChildWindow, Restore
                
                If the routine is called like either of the examples below then default
                processing will occur.  This will merely SetContext on the provided 
                Window and use "CurrentWindow" as the parameter to the command.
                
                t, ParentWindow, ParentWindow, Restore
                t, ChildWindow , ChildWindow , Restore      (normally won't work)
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
        <LI>OpenQA Selenium</LI>
        <LI>AutomatedQA TestComplete</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     **********/
    static public ComponentFunction restore (String winname, String compname) {

        if ( winname == null ) throw new IllegalArgumentException ( "restore.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "restore.compname = null");

        ComponentFunction cf = new ComponentFunction(RESTORE_KEYWORD, winname, compname);
        return cf;
    }


    /*********** <pre> 
                Performs a right-click on any part of a Window based on a stored x,y coordinate.
               
                For components that are unrecognized, like ActiveToolbar menuitems, 
                we can right click on these or any part of a Window based on a stored x,y 
                coordinate.  The window containing the coordinate is first given 
                context and then a right click is generated at the coordinate.  Thus, an item 
                or object can be referenced by name even though it is only recognized
                via coordinates.
                
                The coordinate lookup is done with the component name of the record AND 
                Field #5.
                
                Typical Data Table records:
                
                (1) t MainWindow MainWindow RightClick AnObject
                (2) t MainWindow  ToolItem  RightClick PrintTool
                
                #1 above will contain an AnObject="3,10" entry in the MainWindow section 
                of the Application Map to right click at x=3, y=10 in the MainWindow.
                
                #2 above will contain a ToolItem entry in the MainWindow section with 
                normal recognition information for it .  ToolItem will also have it's
                own section in the Application Map in which there will be an entry like 
                PrintTool="15,30".  This will tell Robot to locate the PrintTool Window 
                object and right click at the coordinates specified by the reference.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param appMapSubkey  Optional:NO 
                Name of the AppMap subkey to lookup and use for the right-click.
              
     **********/
    static public ComponentFunction rightClick (String winname, String compname, String appMapSubkey) {

        if ( winname == null ) throw new IllegalArgumentException ( "rightClick.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "rightClick.compname = null");

        if ( appMapSubkey == null ) throw new IllegalArgumentException ( "rightClick.appMapSubkey = null");
        ComponentFunction cf = new ComponentFunction(RIGHTCLICK_KEYWORD, winname, compname);
        cf.addParameter(appMapSubkey);
        return cf;
    }


    /*********** <pre> 
                Attempts to select a particular menuitem by menuID.
               
                Attempts to select a particular menuitem by menuID.  This is generally 
                used when the menuitem is a bitmap or other item that does not have 
                text.  This value can be retrieved from the the menu by index or by 
                manual lookup from a menu structure output from MenuUtilities.
                The routine first verifies that the specified menuitem exists and exits 
                with error if it does not.  If it does exist then the selection proceeds.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param menuID  Optional:NO 
                MenuID to identify which menuitem to select.
              
     **********/
    static public ComponentFunction selectMenuID (String winname, String compname, String menuID) {

        if ( winname == null ) throw new IllegalArgumentException ( "selectMenuID.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "selectMenuID.compname = null");

        if ( menuID == null ) throw new IllegalArgumentException ( "selectMenuID.menuID = null");
        ComponentFunction cf = new ComponentFunction(SELECTMENUID_KEYWORD, winname, compname);
        cf.addParameter(menuID);
        return cf;
    }


    /*********** <pre> 
                Attempts to select a particular text string menuitem.
               
                Attempts to select a particular text string menuitem.  The menuitem 
                should be specified in the form "Menu->Menu->MenuItem   CTRL+V" 
                with the full text, spaces(if any), and keyboard shortcut text (if
                any).
                
                Ampersands preceding underlined characters are optional.
                The routine first verifies that the specified menuitem exists
                and exits with error if it does not.
                If it does exist then the selection proceeds using the MenuID retrieved
                from the found menuitem.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param textValue  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to select.
              
     **********/
    static public ComponentFunction selectMenuItem (String winname, String compname, String textValue) {

        if ( winname == null ) throw new IllegalArgumentException ( "selectMenuItem.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "selectMenuItem.compname = null");

        if ( textValue == null ) throw new IllegalArgumentException ( "selectMenuItem.textValue = null");
        ComponentFunction cf = new ComponentFunction(SELECTMENUITEM_KEYWORD, winname, compname);
        cf.addParameter(textValue);
        return cf;
    }


    /*********** <pre> 
                Attempts to select a menuitem based on a partial text match.
               
                Attempts to select a menuitem based on a partial text match.  
                The menuitem should be specified in the form "Menu->Menu->MenuItem".
                Each level in the hierarchy can be represented by partial text.
                
                Ampersands preceding underlined characters are optional.
                The routine first verifies that the specified menuitem exists
                and exits with error if it does not.
                If it does exist then the selection proceeds using the MenuID retrieved
                from the found menuitem.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param textValue  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to select.
              
     **********/
    static public ComponentFunction selectMenuItemContains (String winname, String compname, String textValue) {

        if ( winname == null ) throw new IllegalArgumentException ( "selectMenuItemContains.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "selectMenuItemContains.compname = null");

        if ( textValue == null ) throw new IllegalArgumentException ( "selectMenuItemContains.textValue = null");
        ComponentFunction cf = new ComponentFunction(SELECTMENUITEMCONTAINS_KEYWORD, winname, compname);
        cf.addParameter(textValue);
        return cf;
    }


    /*********** <pre> 
                Sends a SetPosition command to the window to set the position, size, and status of the window.
               
                Sends a SetPosition command to the window to set the position, size, 
                and status of the window.  The position, size, and status information 
                is stored in the app map as a subitem in the section for the window.
                The information should be in the format of:
                
                "0,0,640,480;Status=NORMAL"    OR
                "Coords=0,0,640,480;Status=NORMAL"
                
                That example positions the window at 0,0; sizes it to 640 x 480, and
                sets it's status to NORMAL.  Valid values for STATUS are:
                
                NORMAL, MINIMIZED, and MAXIMIZED
                
                The Window SetPosition command has a problem in that it does not want to
                use the same recognition methods used by the other Window commands (like
                SetContext).  Particularly, it does not accept the Type=Window portion
                of these recognition methods.  In addition, if the window is a child
                window of a parent then it expects the ";ChildWindow" add-on in the 
                recognition method.  The child may also need the parent as part of its
                full recognition string like:
                
                ChildWindow=Type=Window;<parent rec>;\;Caption=<caption>;ChildWindow
                
                To handle these child windows, we parse the typical recognition method for 
                our window and attempt to handle these issues.  Once SetContext has 
                successfully set our window, we then remove any "Type=Window" substring 
                if present and add the ";ChildWindow" substring if not present.
                
                To take advantage of this, this routine must be called with the child
                window as a component of the parent window like below:
                
                t, ParentWindow, ChildWindow, SetPosition, ChildPositionReference
                
                If the routine is called like either of the examples below then default
                processing will occur.  This will merely SetContext on the provided 
                Window and use "CurrentWindow" as the parameter to SetPosition.
                
                t, ParentWindow, ParentWindow, SetPosition, ParentPosition
                t, ChildWindow , ChildWindow , SetPosition, ChildPosition   (normally won't work)
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
        <LI>OpenQA Selenium</LI>
        <LI>AutomatedQA TestComplete</LI>
        <LI>OpenQA Selenium</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param presetReference  Optional:NO 
                String specifying a preset reference in the Application for the position, size, and state of the Window.
              
     **********/
    static public ComponentFunction setPosition (String winname, String compname, String presetReference) {

        if ( winname == null ) throw new IllegalArgumentException ( "setPosition.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "setPosition.compname = null");

        if ( presetReference == null ) throw new IllegalArgumentException ( "setPosition.presetReference = null");
        ComponentFunction cf = new ComponentFunction(SETPOSITION_KEYWORD, winname, compname);
        cf.addParameter(presetReference);
        return cf;
    }


    /*********** <pre> 
                 Performs a WindowVP CompareImage OR a RegionImageVP on an object.
               
                Performs a WindowVP CompareImage OR a RegionImageVP on an object.  
                The benchmark VP must already exist and be an asset of the currently 
                running script.
                
                A RegionImageVP can be accomplished by having the name of the VP as an item 
                under the component in the application map.  The item's value must be 
                the coordinate values required by the RegionImageVP (i.e. "65,100,200,250").
                
                Example 1: Perform a WindowVP CompareImage
                
                MainWindow SomeWindowObject VerifyImage StoredVP
                
                (no StoredVP item found in the app map under SomeWindowObject)
                
                The named VP (StoredVP) must not exist in the application map.  The 
                entire panel/object of SomeWindowObject will be captured and compared 
                against the StoredVP baseline which must already exist as an asset of the
                currently running script.
                
                Example 2: Perform a RegionImageVP on a particular area of the screen
                
                MainWindow SomeWindowObject VerifyImage StoredVP
                
                (StoredVP found as:
                 
                "65,100,200,250"   OR
                "Coords=65,100,200,250"
                  
                in the SomeWindowObject section of the app map)
                
                The named VP (StoredVP) is found to exist in the application map as a
                subitem in the SomeWindowObject section of the map.  This causes 
                the routine to attempt a RegionImageVP using the map's value of the StoredVP 
                item as the coordinates for the region to capture.  StoredVP is ALSO the 
                name of the VP which must already exist as an asset of the currently 
                running script.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param vPAsset  Optional:NO 
                TextValue is the name of the pre-existing VP asset stored in the currently running script.
              
     **********/
    static public ComponentFunction verifyImage (String winname, String compname, String vPAsset) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyImage.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyImage.compname = null");

        if ( vPAsset == null ) throw new IllegalArgumentException ( "verifyImage.vPAsset = null");
        ComponentFunction cf = new ComponentFunction(VERIFYIMAGE_KEYWORD, winname, compname);
        cf.addParameter(vPAsset);
        return cf;
    }


    /*********** <pre> 
                Compares the active windows menu system with a benchmark
               
                Retrieves the active windows menu system and outputs the full structure 
                with status to a file.  It then compares that file with the specified 
                benchmark file and sets pass/fail conditions for the test.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param benchmarkFile  Optional:NO 
                name.ext of benchmark file on repositiory's Datapool\Bench directory
              
     @param descriptiveText  Optional:YES 
                Optional expected descriptive text at start of file (first line of bench).
              
     @param testFile  Optional:YES 
                optional name.ext to give current structure in repository's 
                Datapool\Test directory for compare with benchmark.
              
     @param diffFile  Optional:YES 
                Optional name.ext to store difference information
              
     **********/
    static public ComponentFunction verifyMainMenu (String winname, String compname, String benchmarkFile, String descriptiveText, String testFile, String diffFile) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMainMenu.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMainMenu.compname = null");

        if ( benchmarkFile == null ) throw new IllegalArgumentException ( "verifyMainMenu.benchmarkFile = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMAINMENU_KEYWORD, winname, compname);
        cf.addParameter(benchmarkFile);
        cf.addParameter(descriptiveText);
        cf.addParameter(testFile);
        cf.addParameter(diffFile);
        return cf;
    }


    /*********** <pre> 
                Compares the active windows menu system with a benchmark
               
                Retrieves the active windows menu system and outputs the full structure 
                with status to a file.  It then compares that file with the specified 
                benchmark file and sets pass/fail conditions for the test.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        benchmarkFile -- Optional:NO 
                name.ext of benchmark file on repositiory's Datapool\Bench directory
              <BR/>        descriptiveText -- Optional:YES 
                Optional expected descriptive text at start of file (first line of bench).
              <BR/>        testFile -- Optional:YES 
                optional name.ext to give current structure in repository's 
                Datapool\Test directory for compare with benchmark.
              <BR/>        diffFile -- Optional:YES 
                Optional name.ext to store difference information
              
    </UL>

     **********/
    static public ComponentFunction verifyMainMenu(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMainMenu.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMainMenu.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMainMenu.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMAINMENU_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                Attempts to verify the state information of a particular menuitem
                identified by MenuID.
               
                Attempts to verify the state information of a particular menuitem
                identified by MenuID.  This is generally used when the menuitem is a 
                bitmap or other item that does not have text.
                This value can be retrieved from the the menu by index or by manual
                lookup from a menu structure output from MenuUtilities.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param menuID  Optional:NO 
                MenuID to identify which menuitem to test.
              
     @param expectedStatus  Optional:NO 
                Expected status string (or part thereof) to verify. 
              
     **********/
    static public ComponentFunction verifyMenuID (String winname, String compname, String menuID, String expectedStatus) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMenuID.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMenuID.compname = null");

        if ( expectedStatus == null ) throw new IllegalArgumentException ( "verifyMenuID.expectedStatus = null");
        if ( menuID == null ) throw new IllegalArgumentException ( "verifyMenuID.menuID = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMENUID_KEYWORD, winname, compname);
        cf.addParameter(menuID);
        cf.addParameter(expectedStatus);
        return cf;
    }


    /*********** <pre> 
                Attempts to verify the state information of a particular menuitem
                identified by MenuID.
               
                Attempts to verify the state information of a particular menuitem
                identified by MenuID.  This is generally used when the menuitem is a 
                bitmap or other item that does not have text.
                This value can be retrieved from the the menu by index or by manual
                lookup from a menu structure output from MenuUtilities.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        menuID -- Optional:NO 
                MenuID to identify which menuitem to test.
              <BR/>        expectedStatus -- Optional:NO 
                Expected status string (or part thereof) to verify. 
              
    </UL>

     **********/
    static public ComponentFunction verifyMenuID(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMenuID.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMenuID.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuID.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMENUID_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
               Attempts to verify the state information of a particular text string menuitem.
               
                Attempts to verify the state information of a particular text string 
                menuitem.  The menuitem should be specified in the form 
                "Menu->Menu->MenuItem   CTRL+V" with the full text (ampersands optional), 
                spaces(if any), and keyboard shortcut text (if any).  
                (The ampersands precede any character in the menuitem that is underlined.)
                
                Note 1: This command differs from JavaMenuFunctions.VerifyMenuItemContains as this 
                command seeks a Window object that contains a Window's menu.
                
                
                Note 2: For RobotJ engine, this command only supports JavaSwing. It may support other clients in the future.
              	
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param menuItemText  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to test.
              
     @param expectedStatus  Optional:NO 
                Expected status string (or part thereof) to verify. 
              
     **********/
    static public ComponentFunction verifyMenuItem (String winname, String compname, String menuItemText, String expectedStatus) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMenuItem.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMenuItem.compname = null");

        if ( expectedStatus == null ) throw new IllegalArgumentException ( "verifyMenuItem.expectedStatus = null");
        if ( menuItemText == null ) throw new IllegalArgumentException ( "verifyMenuItem.menuItemText = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMENUITEM_KEYWORD, winname, compname);
        cf.addParameter(menuItemText);
        cf.addParameter(expectedStatus);
        return cf;
    }


    /*********** <pre> 
               Attempts to verify the state information of a particular text string menuitem.
               
                Attempts to verify the state information of a particular text string 
                menuitem.  The menuitem should be specified in the form 
                "Menu->Menu->MenuItem   CTRL+V" with the full text (ampersands optional), 
                spaces(if any), and keyboard shortcut text (if any).  
                (The ampersands precede any character in the menuitem that is underlined.)
                
                Note 1: This command differs from JavaMenuFunctions.VerifyMenuItemContains as this 
                command seeks a Window object that contains a Window's menu.
                
                
                Note 2: For RobotJ engine, this command only supports JavaSwing. It may support other clients in the future.
              	
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        menuItemText -- Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to test.
              <BR/>        expectedStatus -- Optional:NO 
                Expected status string (or part thereof) to verify. 
              
    </UL>

     **********/
    static public ComponentFunction verifyMenuItem(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMenuItem.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMenuItem.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuItem.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMENUITEM_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
               Attempts to verify the state information of a menuitem found by partial text match.
               
                Attempts to verify the state information of a menuitem found by partial text match.
                The menuitem should be specified in the form "Menu->Menu->MenuItem".  
                (Optional ampersands precede any character in the menuitem that is underlined.)
                
                Note 1: This command differs from JavaMenuFunctions.VerifyMenuItemContains as this 
                command seeks a Window object that contains a Window's menu.
                
                
                Note 2: For RobotJ engine, this command only supports JavaSwing. It may support other clients in the future.
              	
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param menuItemText  Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to test.
              
     @param expectedStatus  Optional:NO 
                Expected status string (or part thereof) to verify. 
              
     **********/
    static public ComponentFunction verifyMenuItemContains (String winname, String compname, String menuItemText, String expectedStatus) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.compname = null");

        if ( expectedStatus == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.expectedStatus = null");
        if ( menuItemText == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.menuItemText = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMENUITEMCONTAINS_KEYWORD, winname, compname);
        cf.addParameter(menuItemText);
        cf.addParameter(expectedStatus);
        return cf;
    }


    /*********** <pre> 
               Attempts to verify the state information of a menuitem found by partial text match.
               
                Attempts to verify the state information of a menuitem found by partial text match.
                The menuitem should be specified in the form "Menu->Menu->MenuItem".  
                (Optional ampersands precede any character in the menuitem that is underlined.)
                
                Note 1: This command differs from JavaMenuFunctions.VerifyMenuItemContains as this 
                command seeks a Window object that contains a Window's menu.
                
                
                Note 2: For RobotJ engine, this command only supports JavaSwing. It may support other clients in the future.
              	
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Rational RobotJ</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        menuItemText -- Optional:NO 
                Menu->MenuItem hierarchy string to identify which menuitem to test.
              <BR/>        expectedStatus -- Optional:NO 
                Expected status string (or part thereof) to verify. 
              
    </UL>

     **********/
    static public ComponentFunction verifyMenuItemContains(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyMenuItemContains.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYMENUITEMCONTAINS_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


    /*********** <pre> 
                 Performs an UNLOGGED WindowVP CompareImage OR a RegionImageVP on an 
                 object then attempts to retrieve and compare OCR text to the expected 
                 value provided.
               
                Performs an UNLOGGED WindowVP CompareImage OR a RegionImageVP on an 
                object then attempts to retrieve and compare OCR text to the expected 
                value provided.  
                The benchmark VP must already exist and be an asset of the currently 
                running script.
                
                A RegionImageVP can be accomplished by having the name of the VP as an item 
                under the component in the application map.  The item's value must be 
                the coordinate values required by the RegionImageVP 
                (i.e. "Coords=65,100,200,250").
                
                EXAMPLE 1 : Perform a WindowVP CompareImage before OCR Test
                
                t, MainWindow, SomeWindowObject, VerifyOCRValue, StoredVP, 1, "Expected Text"
                
                (no StoredVP item found in the app map under SomeWindowObject)
                
                The named VP (StoredVP) must not exist in the application map if you 
                intend to compare the entire window.  The entire panel/object of 
                SomeWindowObject will be captured and compared against the StoredVP 
                baseline.  This VP must already exist as an asset of the
                currently running script.
                
                EXAMPLE 2 : Perform a RegionImageVP before the OCR test
                
                t, MainWindow, SomeWindowObject, VerifyOCRValue, StoredVP, DataField, "Expected Text"
                
                StoredVP found in Application Map like below:
                
                [SomeWindowObject]
                SomeWindowObject="Type=Something...."
                StoredVP="Coords=65,100,200,250"        --- invokes a RegionImageVP
                ....
                
                When the named VP (StoredVP) is found to exist in the application map as a
                subitem in the SomeWindowObject section of the map then a RegionImageVP 
                will be invoked using the value of the StoredVP item as the coordinates 
                for the region to capture.  
                
                StoredVP is ALSO the name of the VP which must already exist as an asset 
                of the currently running script.
                
                Once the unlogged VP has been completed, we attempt to retrieve the text
                of a predefined OCR region mask that should exist in the VP.  
                
                We can use the OCRRegion value provided from the inputrecord to identify 
                the OCR mask number as needed by the SQAGetOcrRegionText function in Robot.  
                Example 1 above shows we are looking for OCR region #1.
                
                The OCRRegion value in the inputrecord can also be a reference in the 
                Application Map in a section with the same name as the VP as shown below.
                
                [SomeWindowObject]
                SomeWindowObject="Type=Something...."
                StoredVP="Coords=65,100,200,250"
                ....
                
                [StoredVP]
                DataField=1
                AnotherField=2
                ....
                
                Example 2 above shows that we have given region #1 a name of DataField.
                          
                Once retrieved, the OCR text (if any) is compared against the expected 
                results provided.
                  </pre>    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param vPAsset  Optional:NO 
               VPTextValue is the name of the pre-existing VP asset stored in the currently running script.
              
     @param oCRIntegerValue  Optional:NO 
                IntegerValue is the numeric OCR region mask to get the text from.
              
     @param expectedTextValue  Optional:NO 
                Text baseline to compare against the retrieved OCR text.
              
     **********/
    static public ComponentFunction verifyOCRValue (String winname, String compname, String vPAsset, String oCRIntegerValue, String expectedTextValue) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyOCRValue.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyOCRValue.compname = null");

        if ( expectedTextValue == null ) throw new IllegalArgumentException ( "verifyOCRValue.expectedTextValue = null");
        if ( oCRIntegerValue == null ) throw new IllegalArgumentException ( "verifyOCRValue.oCRIntegerValue = null");
        if ( vPAsset == null ) throw new IllegalArgumentException ( "verifyOCRValue.vPAsset = null");
        ComponentFunction cf = new ComponentFunction(VERIFYOCRVALUE_KEYWORD, winname, compname);
        cf.addParameter(vPAsset);
        cf.addParameter(oCRIntegerValue);
        cf.addParameter(expectedTextValue);
        return cf;
    }


    /*********** <pre> 
                 Performs an UNLOGGED WindowVP CompareImage OR a RegionImageVP on an 
                 object then attempts to retrieve and compare OCR text to the expected 
                 value provided.
               
                Performs an UNLOGGED WindowVP CompareImage OR a RegionImageVP on an 
                object then attempts to retrieve and compare OCR text to the expected 
                value provided.  
                The benchmark VP must already exist and be an asset of the currently 
                running script.
                
                A RegionImageVP can be accomplished by having the name of the VP as an item 
                under the component in the application map.  The item's value must be 
                the coordinate values required by the RegionImageVP 
                (i.e. "Coords=65,100,200,250").
                
                EXAMPLE 1 : Perform a WindowVP CompareImage before OCR Test
                
                t, MainWindow, SomeWindowObject, VerifyOCRValue, StoredVP, 1, "Expected Text"
                
                (no StoredVP item found in the app map under SomeWindowObject)
                
                The named VP (StoredVP) must not exist in the application map if you 
                intend to compare the entire window.  The entire panel/object of 
                SomeWindowObject will be captured and compared against the StoredVP 
                baseline.  This VP must already exist as an asset of the
                currently running script.
                
                EXAMPLE 2 : Perform a RegionImageVP before the OCR test
                
                t, MainWindow, SomeWindowObject, VerifyOCRValue, StoredVP, DataField, "Expected Text"
                
                StoredVP found in Application Map like below:
                
                [SomeWindowObject]
                SomeWindowObject="Type=Something...."
                StoredVP="Coords=65,100,200,250"        --- invokes a RegionImageVP
                ....
                
                When the named VP (StoredVP) is found to exist in the application map as a
                subitem in the SomeWindowObject section of the map then a RegionImageVP 
                will be invoked using the value of the StoredVP item as the coordinates 
                for the region to capture.  
                
                StoredVP is ALSO the name of the VP which must already exist as an asset 
                of the currently running script.
                
                Once the unlogged VP has been completed, we attempt to retrieve the text
                of a predefined OCR region mask that should exist in the VP.  
                
                We can use the OCRRegion value provided from the inputrecord to identify 
                the OCR mask number as needed by the SQAGetOcrRegionText function in Robot.  
                Example 1 above shows we are looking for OCR region #1.
                
                The OCRRegion value in the inputrecord can also be a reference in the 
                Application Map in a section with the same name as the VP as shown below.
                
                [SomeWindowObject]
                SomeWindowObject="Type=Something...."
                StoredVP="Coords=65,100,200,250"
                ....
                
                [StoredVP]
                DataField=1
                AnotherField=2
                ....
                
                Example 2 above shows that we have given region #1 a name of DataField.
                          
                Once retrieved, the OCR text (if any) is compared against the expected 
                results provided.
                  </pre>    
    Supporting Engines:
    <P/><UL>
        <LI>Rational Robot</LI>
        <LI>Mercury Interactive WinRunner</LI>
    </UL>

     @param winname  Optional:NO
            The name of the window to act upon.
     @param compname  Optional:NO
            The name of the component to act upon.
     @param parameters  Optional:NO
            An array containing the following parameters:
    <UL>
<BR/>        vPAsset -- Optional:NO 
               VPTextValue is the name of the pre-existing VP asset stored in the currently running script.
              <BR/>        oCRIntegerValue -- Optional:NO 
                IntegerValue is the numeric OCR region mask to get the text from.
              <BR/>        expectedTextValue -- Optional:NO 
                Text baseline to compare against the retrieved OCR text.
              
    </UL>

     **********/
    static public ComponentFunction verifyOCRValue(String winname, String compname, String[] parameters) {

        if ( winname == null ) throw new IllegalArgumentException ( "verifyOCRValue.winname = null");
        if ( compname == null ) throw new IllegalArgumentException ( "verifyOCRValue.compname = null");
        if ( parameters == null ) throw new IllegalArgumentException ( "verifyOCRValue.parameters = null");
        ComponentFunction cf = new ComponentFunction(VERIFYOCRVALUE_KEYWORD, winname, compname);
        cf.addParameters(parameters);
        return cf;
    }


}
