/**
 * Copyright (C) SAS Institute, All rights reserved.
 * General Public License: https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
**/

package org.safs.rest.service.models.version

/**
 * This interface provides a tangible name to use in SAFSREST source code
 * since the actual Version class will be dynamically generated by the
 * Gradle build.
 *
 * While Groovy does not strictly require an interface in this instance,
 * providing the interface will help with the clarity of the code for handling
 * the version.
 *
 * @author Bruce.Faulkner
 * @since August 12, 2015
 *
 */
interface VersionInterface {

    /**
     * Return the current version of SAFSREST.
     * @return String representation of the current verion of SAFSREST in the
     * form <code>0.0.7-SNAPSHOT</code>.
     */
    String getCurrentVersion()
}
